### ISSUE TITLE
/cli is missing in SDK

### ISSUE THREAD

**Issue by andriishupta** [manticoresoftware/manticoresearch-typescript#10]
There are no implementations for https://manual.manticoresearch.com/Connecting_to_the_server/HTTP#/cli and json version

Would be a great enhancement for UtilsApi

**Comment by sanikolaev** [comment]
`/cli` and `/cli_json` are NOT to be used programmatically. There's `/sql` for that and the client includes it - https://github.com/manticoresoftware/manticoresearch-typescript/blob/master/docs/UtilsApi.md#sql
