### ISSUE TITLE
Unable to import manticoresearch

### ISSUE THREAD

**Issue by AngPuoSyer** [manticoresoftware/manticoresearch-typescript#5]
Unable to import manticoresearch into a node project due to `Cannot find module 'manticoresearch-ts' or its corresponding type declarations.ts(2307)`

![image](https://github.com/manticoresoftware/manticoresearch-typescript/assets/95325223/2364119f-6e65-41be-80a6-668cd0f318c6)

node version: v20.9.0
typescript version: v5.3.3
package manager: npm
npm version: v10.1.0

**Comment by Nick-S-2018** [comment]
It's fixed in the new release https://github.com/manticoresoftware/manticoresearch-typescript/releases/tag/4.1.0
